### ISSUE TITLE
Error: invalid_request from Google

### ISSUE THREAD

**Issue by alucena** [gate-sso/gate#106]
Hi,

We are using an Openvpn in our company and wanted to use single sign on with google and the only project I found was gate-sso.
I was setting it up according the documentation of README but I am not able to make it work.

This is my .env:
```
GATE_OAUTH_CLIENT_ID=*******.apps.googleusercontent.com
GATE_OAUTH_CLIENT_SECRET=**********
GATE_HOSTED_DOMAIN=21buttons.com
GATE_SERVER_URL=openvpn.21b.io
GATE_CONFIG_SECRET=secret
GATE_DB_HOST=db
GATE_DB_PORT=3306
GATE_DB_USER=root
GATE_DB_PASSWORD=mysql
CACHE_HOST=redis
CACHE_PORT=6379
GATE_HOSTED_DOMAINS="21buttons.com"
```

When I click to "Sign In with Google" button the following error from a google page appears:

```
400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Missing scheme: openvpn.21b.io/users/auth/google_oauth2/callback
```

And the logs from server (using "make logs") seems to be ok:
```
web_1    | Started GET "/" for 92.211.209.30 at 2018-04-19 11:52:19 +0000
web_1    | Processing by HomeController#index as HTML
web_1    |   Rendered home/index.html.slim within layouts/home (0.6ms)
web_1    | Completed 200 OK in 454ms (Views: 449.4ms | ActiveRecord: 0.0ms)
```

I had to modify docker-compose.yml to create the mysql database in start up because I got an error telling me that the db didn't exist:
```
version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: gate_development
  redis:
    image: redis
  web:
    build: .
    command: rails s -p 80 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      GATE_DB_HOST: db
      GATE_DB_PORT: 3306
      GATE_DB_USER: root
      GATE_DB_PASSWORD: mysql
      CACHE_HOST: redis
      CACHE_PORT: 6379
      GATE_HOSTED_DOMAINS: "21b.io,21buttons.com"
      GATE_SAML_IDP_X509_CERTIFICATE:  "/root/server.crt"
      GATE_SAML_IDP_SECRET_KEY: "/root/server.key"
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
```

Could it be some wrong environment variable value? I don't understand the meaning of some variables like RAILS_ENV, GATE_CONFIG_SECRET, GATE_HOSTED_DOMAINS. What are they for?
